services:

  php:
    build: .
    container_name: php
    volumes:
      - "./:/var/www/html"
      - php_vendor:/var/www/html/vendor
      - php_cache:/var/www/html/cache
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3535:80"
    volumes:
      - "./:/var/www/html"
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - php_vendor:/var/www/html/vendor
      - php_cache:/var/www/html/cache
    depends_on:
      - php

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "my_db"
      POSTGRES_USER: "gordo"
      POSTGRES_PASSWORD: "2004"
    ports:
      - "2004:5432"
    volumes:
      - pgtables:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:snapshot
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "gordo@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "2004"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  puml:
    image: plantuml/plantuml-server:jetty
    container_name: puml
    restart: always
    ports:
      - "4040:8080"
    volumes:
      - "./uml:/var/www/html/uml"

volumes:
  pgtables:
  pgadmin_data:
  php_cache:
  php_vendor:
